-- MySQL Script generated by MySQL Workbench
-- Thu Jun 23 12:00:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Personenverwaltung
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Personenverwaltung
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Personenverwaltung` DEFAULT CHARACTER SET utf8 ;
USE `Personenverwaltung` ;

-- -----------------------------------------------------
-- Table `Personenverwaltung`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Personenverwaltung`.`Person` ;

CREATE TABLE IF NOT EXISTS `Personenverwaltung`.`Person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `gender` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `Person` (`id`, `name`, `lastname`, `email`, `birthdate`, `gender`) VALUES
(1, 'Silvan', 'Dubach', 'silvan.dubach@lernende.bbw.ch', '2004-06-21', 'm'),
(2, 'Maurin', 'Schucan', 'maurin.schucan@lernende.bbw.ch', '2004-012-04', 'm'),
(3, 'Yves', 'Huber', 'yves.huber@lernende.bbw.ch', '2005-11-14', 'm');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
